# Generated by Django 4.0.3 on 2024-04-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgsApp', '0005_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
    ]
